"""add post_treatment_requirements to drawing_analyses

Revision ID: 0821152ab79c
Revises: 4c8162e7b2c9
Create Date: 2026-07-13 00:18:42.481449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0821152ab79c'
down_revision: Union[str, None] = '4c8162e7b2c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drawing_analyses', sa.Column('post_treatment_requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drawing_analyses', 'post_treatment_requirements')
    # ### end Alembic commands ###
