"""add routing templates parts revisions steps

Revision ID: 2e9e80a6c7e9
Revises: 9996e6fbb047
Create Date: 2026-07-12 22:53:04.478404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e9e80a6c7e9'
down_revision: Union[str, None] = '9996e6fbb047'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routing_templates',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('spec', sa.String(length=120), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('part_number', sa.String(length=60), nullable=False),
    sa.Column('revision', sa.String(length=10), nullable=False),
    sa.Column('spec', sa.String(length=120), nullable=False),
    sa.Column('itar', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'part_number', 'revision', name='uq_part_customer_number_revision')
    )
    op.create_table('routing_revisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('routing_template_id', sa.String(length=20), nullable=True),
    sa.Column('part_id', sa.Integer(), nullable=True),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('cloned_from_revision_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('released_by', sa.String(length=120), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('(routing_template_id IS NOT NULL AND part_id IS NULL) OR (routing_template_id IS NULL AND part_id IS NOT NULL)', name='ck_routing_revision_owner_xor'),
    sa.ForeignKeyConstraint(['cloned_from_revision_id'], ['routing_revisions.id'], ),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.ForeignKeyConstraint(['routing_template_id'], ['routing_templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('part_id', 'revision_number', name='uq_routing_rev_part_number'),
    sa.UniqueConstraint('routing_template_id', 'revision_number', name='uq_routing_rev_template_number')
    )
    op.create_index('uq_routing_rev_part_released', 'routing_revisions', ['part_id'], unique=True, postgresql_where="status = 'Released'")
    op.create_index('uq_routing_rev_template_released', 'routing_revisions', ['routing_template_id'], unique=True, postgresql_where="status = 'Released'")
    op.create_table('routing_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('routing_revision_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('parameters', sa.String(length=255), nullable=False),
    sa.Column('work_instruction_doc_no', sa.String(length=30), nullable=True),
    sa.Column('tank_id', sa.String(length=20), nullable=True),
    sa.Column('equipment_id', sa.String(length=20), nullable=True),
    sa.Column('is_final_inspect', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['routing_revision_id'], ['routing_revisions.id'], ),
    sa.ForeignKeyConstraint(['tank_id'], ['tanks.id'], ),
    sa.ForeignKeyConstraint(['work_instruction_doc_no'], ['documents.doc_no'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('customers', sa.Column('require_approved_routing', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('job_operations', sa.Column('is_final_inspect', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('jobs', sa.Column('source_routing_revision_id', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('routing_warning', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'jobs', 'routing_revisions', ['source_routing_revision_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'routing_warning')
    op.drop_column('jobs', 'source_routing_revision_id')
    op.drop_column('job_operations', 'is_final_inspect')
    op.drop_column('customers', 'require_approved_routing')
    op.drop_table('routing_steps')
    op.drop_index('uq_routing_rev_template_released', table_name='routing_revisions', postgresql_where="status = 'Released'")
    op.drop_index('uq_routing_rev_part_released', table_name='routing_revisions', postgresql_where="status = 'Released'")
    op.drop_table('routing_revisions')
    op.drop_table('parts')
    op.drop_table('routing_templates')
    # ### end Alembic commands ###
