"""add pin_lookup_hash for fast operator PIN lookup

Revision ID: 4ae88a1d7995
Revises: 985c17be9bad
Create Date: 2026-07-14 22:47:05.858853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ae88a1d7995'
down_revision: Union[str, None] = '985c17be9bad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pin_lookup_hash', sa.String(length=64), nullable=True))
    op.create_index('ix_users_pin_lookup_hash', 'users', ['pin_lookup_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_pin_lookup_hash', table_name='users')
    op.drop_column('users', 'pin_lookup_hash')
    # ### end Alembic commands ###
