"""add source_drawing_analysis_id to routing_revisions

Revision ID: 4c8162e7b2c9
Revises: 2e9e80a6c7e9
Create Date: 2026-07-12 23:41:58.462538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c8162e7b2c9'
down_revision: Union[str, None] = '2e9e80a6c7e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routing_revisions', sa.Column('source_drawing_analysis_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'routing_revisions', 'drawing_analyses', ['source_drawing_analysis_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'routing_revisions', type_='foreignkey')
    op.drop_column('routing_revisions', 'source_drawing_analysis_id')
    # ### end Alembic commands ###
