"""initial schema

Revision ID: 53d71ebc210b
Revises: 
Create Date: 2026-07-09 10:28:03.229183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '53d71ebc210b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.String(length=60), nullable=False),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('pct_complete', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=False),
    sa.Column('scheduled_for', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('quickbooks_customer_id', sa.String(length=60), nullable=True),
    sa.Column('itar_registered', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('documents',
    sa.Column('doc_no', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('revision', sa.String(length=5), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('owner', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('doc_no')
    )
    op.create_table('equipment',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=False),
    sa.Column('interval_text', sa.String(length=20), nullable=False),
    sa.Column('interval_months', sa.Integer(), nullable=False),
    sa.Column('last_calibrated_at', sa.Date(), nullable=True),
    sa.Column('due_at', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quickbooks_connection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('realm_id', sa.String(length=60), nullable=False),
    sa.Column('access_token', sa.String(length=2000), nullable=False),
    sa.Column('refresh_token', sa.String(length=2000), nullable=False),
    sa.Column('access_token_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('refresh_token_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tanks',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('solution', sa.String(length=120), nullable=False),
    sa.Column('parameter', sa.String(length=60), nullable=False),
    sa.Column('limits_text', sa.String(length=60), nullable=False),
    sa.Column('limit_min', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('limit_max', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('analysis_interval_days', sa.Integer(), nullable=False),
    sa.Column('last_result', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('last_analyzed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('held', sa.Boolean(), nullable=False),
    sa.Column('hold_reason', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('initials', sa.String(length=4), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=60), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('pin_hash', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('approval_basis', sa.String(length=200), nullable=False),
    sa.Column('otd_pct', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('survey_due_at', sa.Date(), nullable=True),
    sa.Column('survey_overdue', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('webhook_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=60), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('delivered', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calibration_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.String(length=20), nullable=False),
    sa.Column('performed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('performed_by', sa.String(length=120), nullable=False),
    sa.Column('result', sa.String(length=40), nullable=False),
    sa.Column('next_due_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_lots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chemical_name', sa.String(length=160), nullable=False),
    sa.Column('lot_number', sa.String(length=40), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('on_hand_qty', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('on_hand_unit', sa.String(length=10), nullable=False),
    sa.Column('reorder_at_qty', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('expires_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lot_number')
    )
    op.create_table('invoices',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('terms', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('qb_sync_status', sa.String(length=20), nullable=False),
    sa.Column('quickbooks_invoice_id', sa.String(length=60), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('customer_po', sa.String(length=60), nullable=False),
    sa.Column('part_number', sa.String(length=60), nullable=False),
    sa.Column('revision', sa.String(length=10), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('material_lot', sa.String(length=40), nullable=False),
    sa.Column('process_label', sa.String(length=120), nullable=False),
    sa.Column('spec', sa.String(length=120), nullable=False),
    sa.Column('spec_note', sa.String(length=255), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('due_note', sa.String(length=120), nullable=False),
    sa.Column('itar', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('governing_doc_no', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['governing_doc_no'], ['documents.doc_no'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portal_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('tank_additions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tank_id', sa.String(length=10), nullable=False),
    sa.Column('chemical', sa.String(length=120), nullable=False),
    sa.Column('amount', sa.String(length=60), nullable=False),
    sa.Column('added_by', sa.String(length=120), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['tank_id'], ['tanks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tank_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tank_id', sa.String(length=10), nullable=False),
    sa.Column('result', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('in_limit', sa.Boolean(), nullable=False),
    sa.Column('analyzed_by', sa.String(length=120), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['tank_id'], ['tanks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('certificates',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('job_id', sa.String(length=20), nullable=False),
    sa.Column('qty_accepted', sa.Integer(), nullable=False),
    sa.Column('process_text', sa.String(length=255), nullable=False),
    sa.Column('issued', sa.Boolean(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('issued_by', sa.String(length=120), nullable=True),
    sa.Column('blocked_reason', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.String(length=20), nullable=False),
    sa.Column('job_id', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_operations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=20), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('parameters', sa.String(length=255), nullable=False),
    sa.Column('work_instruction_doc_no', sa.String(length=30), nullable=True),
    sa.Column('tank_id', sa.String(length=10), nullable=True),
    sa.Column('equipment_id', sa.String(length=20), nullable=True),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('signed_by', sa.String(length=120), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tank_ooc_at_signoff', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['tank_id'], ['tanks.id'], ),
    sa.ForeignKeyConstraint(['work_instruction_doc_no'], ['documents.doc_no'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ncrs',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('job_id', sa.String(length=20), nullable=True),
    sa.Column('tank_id', sa.String(length=10), nullable=True),
    sa.Column('reference_label', sa.String(length=40), nullable=False),
    sa.Column('opened_at', sa.Date(), nullable=False),
    sa.Column('disposition', sa.String(length=40), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['tank_id'], ['tanks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('customer_po', sa.String(length=60), nullable=False),
    sa.Column('part_number', sa.String(length=60), nullable=False),
    sa.Column('spec', sa.String(length=120), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('converted_job_id', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['converted_job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('capas',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('ncr_id', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('closed_date', sa.Date(), nullable=True),
    sa.Column('phase', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['ncr_id'], ['ncrs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_lines')
    op.drop_table('capas')
    op.drop_table('orders')
    op.drop_table('ncrs')
    op.drop_table('job_operations')
    op.drop_table('invoice_lines')
    op.drop_table('certificates')
    op.drop_table('tank_analyses')
    op.drop_table('tank_additions')
    op.drop_table('portal_users')
    op.drop_table('jobs')
    op.drop_table('invoices')
    op.drop_table('inventory_lots')
    op.drop_table('calibration_records')
    op.drop_table('webhook_events')
    op.drop_table('vendors')
    op.drop_table('users')
    op.drop_table('tanks')
    op.drop_table('quickbooks_connection')
    op.drop_table('equipment')
    op.drop_table('documents')
    op.drop_table('customers')
    op.drop_table('audit_programs')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
