"""add C of C traceability snapshot columns

Revision ID: 5fb948dc28de
Revises: 6348c6e846f7
Create Date: 2026-07-13 20:35:55.961006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5fb948dc28de'
down_revision: Union[str, None] = '6348c6e846f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificates', sa.Column('material_lot', sa.String(length=40), nullable=True))
    op.add_column('certificates', sa.Column('part_number', sa.String(length=60), nullable=True))
    op.add_column('certificates', sa.Column('revision', sa.String(length=10), nullable=True))
    op.add_column('certificates', sa.Column('spec', sa.String(length=120), nullable=True))
    op.add_column('certificates', sa.Column('routing_revision_label', sa.String(length=60), nullable=True))
    op.add_column('certificates', sa.Column('recorded_readings', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('certificates', 'recorded_readings')
    op.drop_column('certificates', 'routing_revision_label')
    op.drop_column('certificates', 'spec')
    op.drop_column('certificates', 'revision')
    op.drop_column('certificates', 'part_number')
    op.drop_column('certificates', 'material_lot')
    # ### end Alembic commands ###
