"""add purchase order analysis, order line routing fields, job po requirements

Revision ID: 6348c6e846f7
Revises: 889bcfbba2e5
Create Date: 2026-07-13 16:17:00.689387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6348c6e846f7'
down_revision: Union[str, None] = '889bcfbba2e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_order_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('po_number', sa.String(length=60), nullable=True),
    sa.Column('po_date', sa.Date(), nullable=True),
    sa.Column('customer_name_guess', sa.String(length=200), nullable=True),
    sa.Column('general_requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('line_items', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('raw_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_used', sa.String(length=60), nullable=True),
    sa.Column('created_by', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('jobs', sa.Column('po_requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('order_lines', sa.Column('part_number', sa.String(length=60), nullable=True))
    op.add_column('order_lines', sa.Column('revision', sa.String(length=10), nullable=True))
    op.add_column('order_lines', sa.Column('spec', sa.String(length=120), nullable=True))
    op.add_column('order_lines', sa.Column('job_id', sa.String(length=20), nullable=True))
    op.create_foreign_key(None, 'order_lines', 'jobs', ['job_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_lines', type_='foreignkey')
    op.drop_column('order_lines', 'job_id')
    op.drop_column('order_lines', 'spec')
    op.drop_column('order_lines', 'revision')
    op.drop_column('order_lines', 'part_number')
    op.drop_column('jobs', 'po_requirements')
    op.drop_table('purchase_order_analyses')
    # ### end Alembic commands ###
