"""add overall_thickness fields to drawing_analyses

Revision ID: 7afddacc82fc
Revises: de82f33c5874
Create Date: 2026-07-13 12:44:21.049531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7afddacc82fc'
down_revision: Union[str, None] = 'de82f33c5874'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drawing_analyses', sa.Column('overall_thickness_in', sa.Float(), nullable=True))
    op.add_column('drawing_analyses', sa.Column('overall_thickness_source', sa.Text(), nullable=True))
    op.add_column('drawing_analyses', sa.Column('overall_thickness_confidence', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drawing_analyses', 'overall_thickness_confidence')
    op.drop_column('drawing_analyses', 'overall_thickness_source')
    op.drop_column('drawing_analyses', 'overall_thickness_in')
    # ### end Alembic commands ###
