"""add contract review, customer gate flags, order PO link

Revision ID: 7c4382e25e72
Revises: 5fb948dc28de
Create Date: 2026-07-13 22:23:53.139697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7c4382e25e72'
down_revision: Union[str, None] = '5fb948dc28de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(length=20), nullable=False),
    sa.Column('customer_requirements_reviewed', sa.Boolean(), nullable=False),
    sa.Column('spec_and_revision_confirmed', sa.Boolean(), nullable=False),
    sa.Column('special_requirements_understood', sa.Boolean(), nullable=False),
    sa.Column('regulatory_itar_reviewed', sa.Boolean(), nullable=False),
    sa.Column('approved_process_available', sa.Boolean(), nullable=False),
    sa.Column('capacity_confirmed', sa.Boolean(), nullable=False),
    sa.Column('differences_resolved', sa.Boolean(), nullable=False),
    sa.Column('governing_spec', sa.String(length=120), nullable=False),
    sa.Column('spec_revision', sa.String(length=30), nullable=False),
    sa.Column('captured_requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by', sa.String(length=120), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.add_column('customers', sa.Column('requires_contract_review', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('customers', sa.Column('quality_standards', sa.String(length=200), server_default='', nullable=False))
    op.add_column('orders', sa.Column('purchase_order_analysis_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'purchase_order_analyses', ['purchase_order_analysis_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'purchase_order_analysis_id')
    op.drop_column('customers', 'quality_standards')
    op.drop_column('customers', 'requires_contract_review')
    op.drop_table('contract_reviews')
    # ### end Alembic commands ###
