"""add email intake state and log tables

Revision ID: 889bcfbba2e5
Revises: 7afddacc82fc
Create Date: 2026-07-13 13:02:43.109370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '889bcfbba2e5'
down_revision: Union[str, None] = '7afddacc82fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_intake_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_poll_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_error_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_intake_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.String(length=998), nullable=False),
    sa.Column('sender', sa.String(length=320), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('attachment_filename', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('drawing_analysis_id', sa.Integer(), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['drawing_analysis_id'], ['drawing_analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_intake_log_message_id'), 'email_intake_log', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_intake_log_message_id'), table_name='email_intake_log')
    op.drop_table('email_intake_log')
    op.drop_table('email_intake_state')
    # ### end Alembic commands ###
