"""add drawing_analyses table

Revision ID: 8e2d76b1ef64
Revises: bdea516fee4b
Create Date: 2026-07-09 15:24:20.033247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8e2d76b1ef64'
down_revision: Union[str, None] = 'bdea516fee4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drawing_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('part_number', sa.String(length=120), nullable=True),
    sa.Column('revision', sa.String(length=30), nullable=True),
    sa.Column('material', sa.String(length=200), nullable=True),
    sa.Column('processing_requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('governing_specs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('masking_requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dimensions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('surface_area_sq_in', sa.Float(), nullable=True),
    sa.Column('surface_area_method', sa.Text(), nullable=True),
    sa.Column('surface_area_confidence', sa.String(length=10), nullable=True),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('raw_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_used', sa.String(length=60), nullable=True),
    sa.Column('created_by', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drawing_analyses')
    # ### end Alembic commands ###
