"""add planning gate and file storage

Revision ID: 985c17be9bad
Revises: 7c4382e25e72
Create Date: 2026-07-14 16:13:39.424873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '985c17be9bad'
down_revision: Union[str, None] = '7c4382e25e72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drawing_analyses', sa.Column('stored_file_path', sa.String(length=500), nullable=True))
    op.add_column('jobs', sa.Column('planning_status', sa.String(length=20), server_default='Planned', nullable=False))
    op.add_column('jobs', sa.Column('source_drawing_analysis_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'jobs', 'drawing_analyses', ['source_drawing_analysis_id'], ['id'])
    op.add_column('purchase_order_analyses', sa.Column('stored_file_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_order_analyses', 'stored_file_path')
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'source_drawing_analysis_id')
    op.drop_column('jobs', 'planning_status')
    op.drop_column('drawing_analyses', 'stored_file_path')
    # ### end Alembic commands ###
