"""add active flag to customers vendors equipment

Revision ID: 9996e6fbb047
Revises: 8e2d76b1ef64
Create Date: 2026-07-12 22:01:23.839120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9996e6fbb047'
down_revision: Union[str, None] = '8e2d76b1ef64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('equipment', sa.Column('active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('vendors', sa.Column('active', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendors', 'active')
    op.drop_column('equipment', 'active')
    op.drop_column('customers', 'active')
    # ### end Alembic commands ###
