"""add attachments table and job_operations.source_routing_step_id

Revision ID: 9dae8bea77b3
Revises: 4ae88a1d7995
Create Date: 2026-07-14 22:56:24.097718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dae8bea77b3'
down_revision: Union[str, None] = '4ae88a1d7995'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.String(length=60), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('is_quality_alert', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('stored_file_path', sa.String(length=500), nullable=False),
    sa.Column('uploaded_by', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_attachments_entity', 'attachments', ['entity_type', 'entity_id'], unique=False)
    op.add_column('job_operations', sa.Column('source_routing_step_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'job_operations', 'routing_steps', ['source_routing_step_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job_operations', type_='foreignkey')
    op.drop_column('job_operations', 'source_routing_step_id')
    op.drop_index('ix_attachments_entity', table_name='attachments')
    op.drop_table('attachments')
    # ### end Alembic commands ###
