"""add external_id columns for real data import

Revision ID: 9ee04fdac4c2
Revises: f1b8fd7dfabe
Create Date: 2026-07-09 11:26:18.740653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ee04fdac4c2'
down_revision: Union[str, None] = 'f1b8fd7dfabe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('capas', sa.Column('external_id', sa.String(length=60), nullable=True))
    op.create_unique_constraint(None, 'capas', ['external_id'])
    op.add_column('certificates', sa.Column('external_id', sa.String(length=60), nullable=True))
    op.create_unique_constraint(None, 'certificates', ['external_id'])
    op.add_column('customers', sa.Column('external_id', sa.String(length=60), nullable=True))
    op.create_unique_constraint(None, 'customers', ['external_id'])
    op.add_column('documents', sa.Column('external_id', sa.String(length=60), nullable=True))
    op.create_unique_constraint(None, 'documents', ['external_id'])
    op.add_column('inventory_lots', sa.Column('external_id', sa.String(length=60), nullable=True))
    op.alter_column('inventory_lots', 'vendor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(None, 'inventory_lots', ['external_id'])
    op.add_column('invoice_lines', sa.Column('description', sa.String(length=255), nullable=False, server_default=''))
    op.alter_column('invoice_lines', 'description', server_default=None)
    op.alter_column('invoice_lines', 'job_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.add_column('invoices', sa.Column('external_id', sa.String(length=60), nullable=True))
    op.create_unique_constraint(None, 'invoices', ['external_id'])
    op.add_column('job_operations', sa.Column('external_id', sa.String(length=60), nullable=True))
    op.create_unique_constraint(None, 'job_operations', ['external_id'])
    op.add_column('jobs', sa.Column('external_id', sa.String(length=60), nullable=True))
    op.create_unique_constraint(None, 'jobs', ['external_id'])
    op.add_column('ncrs', sa.Column('external_id', sa.String(length=60), nullable=True))
    op.create_unique_constraint(None, 'ncrs', ['external_id'])
    op.add_column('orders', sa.Column('external_id', sa.String(length=60), nullable=True))
    op.create_unique_constraint(None, 'orders', ['external_id'])
    op.add_column('portal_users', sa.Column('external_id', sa.String(length=60), nullable=True))
    op.create_unique_constraint(None, 'portal_users', ['external_id'])
    op.add_column('tanks', sa.Column('external_id', sa.String(length=60), nullable=True))
    op.create_unique_constraint(None, 'tanks', ['external_id'])
    op.add_column('users', sa.Column('external_id', sa.String(length=60), nullable=True))
    op.create_unique_constraint(None, 'users', ['external_id'])
    op.add_column('vendors', sa.Column('external_id', sa.String(length=60), nullable=True))
    op.create_unique_constraint(None, 'vendors', ['external_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vendors', type_='unique')
    op.drop_column('vendors', 'external_id')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'external_id')
    op.drop_constraint(None, 'tanks', type_='unique')
    op.drop_column('tanks', 'external_id')
    op.drop_constraint(None, 'portal_users', type_='unique')
    op.drop_column('portal_users', 'external_id')
    op.drop_constraint(None, 'orders', type_='unique')
    op.drop_column('orders', 'external_id')
    op.drop_constraint(None, 'ncrs', type_='unique')
    op.drop_column('ncrs', 'external_id')
    op.drop_constraint(None, 'jobs', type_='unique')
    op.drop_column('jobs', 'external_id')
    op.drop_constraint(None, 'job_operations', type_='unique')
    op.drop_column('job_operations', 'external_id')
    op.drop_constraint(None, 'invoices', type_='unique')
    op.drop_column('invoices', 'external_id')
    op.alter_column('invoice_lines', 'job_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('invoice_lines', 'description')
    op.drop_constraint(None, 'inventory_lots', type_='unique')
    op.alter_column('inventory_lots', 'vendor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('inventory_lots', 'external_id')
    op.drop_constraint(None, 'documents', type_='unique')
    op.drop_column('documents', 'external_id')
    op.drop_constraint(None, 'customers', type_='unique')
    op.drop_column('customers', 'external_id')
    op.drop_constraint(None, 'certificates', type_='unique')
    op.drop_column('certificates', 'external_id')
    op.drop_constraint(None, 'capas', type_='unique')
    op.drop_column('capas', 'external_id')
    # ### end Alembic commands ###
