"""add external_id to invoice_lines

Revision ID: cdb8740ae34d
Revises: 39df0c5e554f
Create Date: 2026-07-09 11:36:59.194199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdb8740ae34d'
down_revision: Union[str, None] = '39df0c5e554f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_lines', sa.Column('external_id', sa.String(length=60), nullable=True))
    op.create_unique_constraint(None, 'invoice_lines', ['external_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoice_lines', type_='unique')
    op.drop_column('invoice_lines', 'external_id')
    # ### end Alembic commands ###
