"""add required and recorded process parameters to routing_steps and job_operations

Revision ID: de82f33c5874
Revises: 0821152ab79c
Create Date: 2026-07-13 01:41:10.541890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'de82f33c5874'
down_revision: Union[str, None] = '0821152ab79c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_operations', sa.Column('required_parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('job_operations', sa.Column('recorded_parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('job_operations', sa.Column('has_out_of_spec_reading', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('routing_steps', sa.Column('required_parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routing_steps', 'required_parameters')
    op.drop_column('job_operations', 'has_out_of_spec_reading')
    op.drop_column('job_operations', 'recorded_parameters')
    op.drop_column('job_operations', 'required_parameters')
    # ### end Alembic commands ###
