"""relax inventory lot_number uniqueness

Revision ID: eece1aa68f61
Revises: cdb8740ae34d
Create Date: 2026-07-09 11:43:31.372020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eece1aa68f61'
down_revision: Union[str, None] = 'cdb8740ae34d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('inventory_lots_lot_number_key', 'inventory_lots', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('inventory_lots_lot_number_key', 'inventory_lots', ['lot_number'])
    # ### end Alembic commands ###
