"""add company metrics

Revision ID: f1b8fd7dfabe
Revises: 53d71ebc210b
Create Date: 2026-07-09 10:35:40.685300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1b8fd7dfabe'
down_revision: Union[str, None] = '53d71ebc210b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_metrics',
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('value', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('updated_at', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_metrics')
    # ### end Alembic commands ###
